name: Tests

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install bats
        run: |
          sudo apt-get update -qq && sudo apt-get install -yqq bats

      - name: Run bats tests
        run: |
          cd $GITHUB_WORKSPACE && bats tests/*.bats
